language: python
os: linux

python:
  - 3.8

env:
  - SECRET_KEY='django-insecure-#cqhtip#_$ek$ail5(e#=_df_)279o#f)h$md_p38n*ukq1w^_'
    DATABASE_HOST=ec2-3-230-238-86.compute-1.amazonaws.com
    DATABASE_NAME=d7gmg5ku8a32om
    DATABASE_USER=rxbooyqynrvkvq
    DATABASE_PASSWORD=75afc573487744c5fcd6f4580bf0adc20ad8a629367e2358d783eaa50b8187bf
    EMAIL_HOST_USER=nyc.greencan@gmail.com
    EMAIL_HOST_PASSWORD=Tandon123
    TEST_DATABASE_HOST=ec2-3-230-238-86.compute-1.amazonaws.com
    TEST_DATABASE_NAME=d7gmg5ku8a32om
    TEST_DATABASE_USER=rxbooyqynrvkvq
    TEST_DATABASE_PASSWORD=75afc573487744c5fcd6f4580bf0adc20ad8a629367e2358d783eaa50b8187bf
    FIRE_STORAGE_API_KEY=AIzaSyDTyK0Z4z6YPG_gx7Ue8bS7Nasv747a5-8
    FIRE_MESSAGE_SENDER_ID=957653486728
    FIRE_APP_ID=ddb27d2cf6067972c6e33d

install:
  - pip install -r requirements.txt

before_script:
  - python ./greenCan/manage.py makemigrations
  - python ./greenCan/manage.py migrate

script:
  - python -m black . --check --line-length=99
  - python -m flake8 --exclude=migrations --max-line-length=99
  - python greenCan/manage.py collectstatic
  - cd greenCan && python -m coverage run --source=accounts,home,reuse,recycle,rewards,reduce,helper,moderation,notification manage.py test --keepdb

after_success:
  - python -m coveralls
